{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flashcards.fullname" . }}-postgres-secret
  labels:
    {{- include "flashcards.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ required "postgres.password is required — pass via --set postgres.password=<value>" .Values.postgres.password | quote }}
{{- end }}
