apiVersion: v1
kind: Service
metadata:
  name: {{ include "flashcards.fullname" . }}
  labels:
    {{- include "flashcards.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "flashcards.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
