import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { shuffleArray, mapRawCardToStudyCard } from "./get-random-card";

// ---------------------------------------------------------------------------
// shuffleArray
// ---------------------------------------------------------------------------

describe("shuffleArray", () => {
  it("returns the same array reference", () => {
    const arr = [1, 2, 3];
    const result = shuffleArray(arr);
    assert.equal(result, arr);
  });

  it("preserves all elements", () => {
    const arr = ["a", "b", "c", "d"];
    shuffleArray(arr);
    assert.deepEqual([...arr].sort(), ["a", "b", "c", "d"]);
  });

  it("handles an empty array", () => {
    assert.deepEqual(shuffleArray([]), []);
  });

  it("handles a single element", () => {
    assert.deepEqual(shuffleArray([42]), [42]);
  });
});

// ---------------------------------------------------------------------------
// mapRawCardToStudyCard
// ---------------------------------------------------------------------------

const RAW_MC = {
  id: "card-1",
  type: "MULTIPLE_CHOICE" as const,
  question: "What is lift?",
  answer: "Upward aerodynamic force",
  explanation: "Lift is generated by the wing.",
  choices: [
    { id: "c1", text: "Gravity", isCorrect: false },
    { id: "c2", text: "Upward aerodynamic force", isCorrect: true },
    { id: "c3", text: "Thrust", isCorrect: false },
    { id: "c4", text: "Drag", isCorrect: false },
  ],
  references: [{ label: "FTM Chapter 1", url: null }],
};

const RAW_OA = {
  id: "card-2",
  type: "OPEN_ANSWER" as const,
  question: "Define angle of attack.",
  answer: "The angle between the chord line and the relative airflow.",
  explanation: null,
  choices: [],
  references: [],
};

describe("mapRawCardToStudyCard — multiple choice", () => {
  it("returns type MULTIPLE_CHOICE", () => {
    const card = mapRawCardToStudyCard(RAW_MC);
    assert.equal(card.type, "MULTIPLE_CHOICE");
  });

  it("maps all scalar fields correctly", () => {
    const card = mapRawCardToStudyCard(RAW_MC);
    assert.equal(card.id, "card-1");
    assert.equal(card.question, "What is lift?");
    assert.equal(card.answer, "Upward aerodynamic force");
    assert.equal(card.explanation, "Lift is generated by the wing.");
  });

  it("maps choices to StudyCardChoice shape", () => {
    const card = mapRawCardToStudyCard(RAW_MC);
    if (card.type !== "MULTIPLE_CHOICE") throw new Error("wrong type");
    assert.equal(card.choices.length, 4);
    const correct = card.choices.find((c) => c.isCorrect);
    assert.ok(correct);
    assert.equal(correct.text, "Upward aerodynamic force");
  });

  it("maps the first reference", () => {
    const card = mapRawCardToStudyCard(RAW_MC);
    assert.deepEqual(card.reference, { label: "FTM Chapter 1", url: null });
  });

  it("sets reference to null when references array is empty", () => {
    const card = mapRawCardToStudyCard({ ...RAW_MC, references: [] });
    assert.equal(card.reference, null);
  });
});

describe("mapRawCardToStudyCard — open answer", () => {
  it("returns type OPEN_ANSWER", () => {
    const card = mapRawCardToStudyCard(RAW_OA);
    assert.equal(card.type, "OPEN_ANSWER");
  });

  it("maps all scalar fields correctly", () => {
    const card = mapRawCardToStudyCard(RAW_OA);
    assert.equal(card.id, "card-2");
    assert.equal(card.answer, "The angle between the chord line and the relative airflow.");
    assert.equal(card.explanation, null);
    assert.equal(card.reference, null);
  });
});
